require 'yaml'
require 'pry'
require 'i18n'

I18n.load_path << Dir["#{File.expand_path('config/locales', __dir__)}/*.yml"]

require_relative 'errors/terminate'
require_relative 'helpers/console_helper'
require_relative 'entities/put_money_result'
require_relative 'entities/withdraw_money_result'
require_relative 'entities/send_money_result'
require_relative 'entities/base_card'
require_relative 'entities/capitalist_card'
require_relative 'entities/usual_card'
require_relative 'entities/virtual_card'
require_relative 'entities/account'
require_relative 'inputs/base_input'
require_relative 'inputs/number_input'
require_relative 'inputs/command_input'
require_relative 'inputs/card_type_input'
require_relative 'inputs/select_card_input'
require_relative 'inputs/put_money_input'
require_relative 'inputs/withdraw_money_input'
require_relative 'inputs/send_money_input'
require_relative 'store/yaml_store'
require_relative 'manager/data_manager'
require_relative 'console/base_console'
require_relative 'console/base_console'
require_relative 'console/account_console'
require_relative 'console/card_console'
require_relative 'console/money_console'
require_relative 'console/root_console'
